[package]
name = "agent-common"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bincode = "1.3.3"
byteorder = "1.4.3"
schemars = { version = "0.8.8", features = ["uuid", "chrono"] }
uuid = { version = "0.8.2", features = ["serde"] }
chrono = { version = "0.4.19", features = ["serde"] }
ring = "0.16.20"

[dev-dependencies]
hex = "0.4.3"