[package]
name = "playit-agent-proto"
version.workspace = true
edition = "2021"
description = "Contains the protocol messages for a playit.gg agent"
license = "BSD-2-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { workspace = true }
hex = { workspace = true }
byteorder = { workspace = true }

sha2 = "0.10"
hmac = "0.12"

[dev-dependencies]
rand = { workspace = true }
